# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bc55d0ae76e6db72b69ad14596f98bd74c526d97a9cb5fcd9b63a5499d81d84089e98e788ce4189e1b0584d6d3ddba8a5fcf3230a003e7b1e621de0417e8096

test:
  secret_key_base: ef4a699f889e5a324e2fcb16ba3e87dc82ec0e01cd8fc2395fc4cf3fe4f730defcdae499a9264851dfd00b6b2b0afea9cf4f60d854cce9fdf883c634600ce72c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
